### ISSUE TITLE
Sorry, still dont work

### ISSUE THREAD

**Issue by cooliobr** [immstudios/nebula-demo#3]
Sorry Martin, still not working , same problem in pg.

You have any specification to install this demo ?
Linux distro?
Kernel ?
i already tried 
Ubuntu 18.04, 20 
Debian 10

**Comment by martastain** [comment]
That's weird. I just tried it on a clean machine and it worked. 
Debian 11
Docker version 20.10.12, build e91ed57
Docker Compose version v2.2.3

Could you try to remove everything first (run `docker-compose down -v --rmi all`, then `git pull` and run `./install.sh` again)?

**Comment by cooliobr** [comment]
I will try a new machine.


Att.

Rafael Machado
HALLO! Media Group.
REGS IT LTDA.
ANTIK Business Representative BRASIL
"Believe in the future, believe in your success"
"Não existe patch para a estupidez humana"





Em qui., 24 de fev. de 2022 às 16:58, Martin Wacker <
***@***.***> escreveu:

**Comment by cooliobr** [comment]
After intall full docker-compose and docker, it works, if i install only full docker-compose i face this error
